# Generated by Django 4.0.2 on 2022-02-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Select_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_city', models.CharField(max_length=250)),
                ('drop_city', models.CharField(max_length=250)),
                ('truck_type', models.CharField(choices=[('ACE / DOST / PICKUP (1.5 TON)', 'ACE / DOST / PICKUP (1.5 TON)'), ('TATA 407 / EICHER 14FT (4 TON)', 'TATA 407 / EICHER 14FT (4 TON)'), ('EICHER 17FT (5 TON)', 'EICHER 17FT (5 TON)'), ('EICHER 19FT (7 TON)', 'EICHER 19FT (7 TON)'), ('20FT CONTAINER (6.5 TON)', '20FT CONTAINER (6.5 TON)'), ('TATA TRUCK (10 TON)', 'TATA TRUCK (10 TON)'), ('32FT CONTAINER (7 TON)', '32FT CONTAINER (7 TON)'), ('32FT CONTAINER (14 TON)', '32FT CONTAINER (14 TON)'), ('32 / 40 FEET OPEN TRAILER', '32 / 40 FEET OPEN TRAILER'), ('SELECT TRUCK LATER', 'SELECT TRUCK LATER'), ('TAURUS (18 TON) N.A', 'TAURUS (18 TON) N.A'), ('PARCEL SERVIC', 'PARCEL SERVIC')], max_length=250)),
                ('Select_date_type', models.DateField()),
                ('Select_good_type', models.CharField(max_length=230)),
                ('Select_customer_type', models.CharField(choices=[('Individual (Persanol Goods)', 'Indivisual (Persanol Goods)'), ('Company (Industrial/Commercial Goods)', 'Company (Industrial/Commercial Goods)'), ('Transpoter', 'Transpoter'), ('Truck Owner', 'Truck Owner')], max_length=250)),
                ('enter_weight', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=90)),
                ('last_name', models.CharField(blank=True, max_length=90)),
                ('email', models.EmailField(max_length=250)),
                ('Company_name_or_shop_name', models.CharField(max_length=250)),
                ('GST_Number', models.CharField(blank=True, max_length=250)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
